In [7]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
import pickle

In [8]:
data=pd.read_csv('../Datasets/Churn_Modelling.csv')
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [9]:
# Preprocess the data
data = data.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1)

In [10]:
data.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [11]:
# Encode categorical variables

label_encoder_gender = LabelEncoder()
data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])

In [12]:
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [13]:
# One-hot encode 'Geography'

onehot_encoder_geo = OneHotEncoder(handle_unknown='ignore')
geo_encoded = onehot_encoder_geo.fit_transform(data[['Geography']]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded, columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [14]:
# Combine one-hot encoded columns with original data
data = pd.concat([data.drop('Geography', axis=1), geo_encoded_df], axis=1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [15]:
# Split the data into features and target
X = data.drop('EstimatedSalary', axis=1)
y = data['EstimatedSalary']

In [16]:
## Split the data in training and tetsing sets
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [17]:
## Scale these features
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [18]:
# Save the encoders and scaler for later use
with open('../Models/label_encoder_gender.pkl', 'wb') as file:
    pickle.dump(label_encoder_gender, file)

with open('../Models/onehot_encoder_geo.pkl', 'wb') as file:
    pickle.dump(onehot_encoder_geo, file)

with open('../Models/scaler.pkl', 'wb') as file:
    pickle.dump(scaler, file)

#### ANN Regression Problem statement

In [19]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [20]:
# Build the model
model = Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(32, activation='relu'),
    Dense(1)  # Output layer for regression
])

## compile the model
model.compile(optimizer='adam',loss='mean_absolute_error',metrics=['mae'])

model.summary()

c:\Users\Hp\AppData\Local\Programs\Python\Python313\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [21]:
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

# Set up TensorBoard
log_dir = "regressionlogs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

In [22]:
# Set up Early Stopping
early_stopping_callback = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

In [23]:
# Train the model
history = model.fit(
    X_train, y_train,
    validation_data=(X_test, y_test),
    epochs=100,
    callbacks=[early_stopping_callback, tensorboard_callback]
)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 100383.3438 - mae: 100383.3438 - val_loss: 98537.7734 - val_mae: 98537.7734
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 99697.1094 - mae: 99697.1094 - val_loss: 97150.0078 - val_mae: 97150.0078
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 97269.8281 - mae: 97269.8281 - val_loss: 93583.4062 - val_mae: 93583.4062
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 92442.6328 - mae: 92442.6328 - val_loss: 87564.0859 - val_mae: 87564.0859
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 85339.0312 - mae: 85339.0312 - val_loss: 79715.6406 - val_mae: 79715.6406
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 76832.8281 - mae: 76832.8281 - val_loss: 71241.3438 - val_mae: 71241.3438
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 68285.5391 - mae: 68285.5391 - val_loss: 63554.5391 - val_mae: 63554.5391
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 60995.8672 - mae: 60995.8672 - val_loss: 57672.3281 - val_mae: 57672.3281
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 55922.6602 - mae: 55922.6602 - val_loss: 54009.6055 - val_mae: 54009.6055
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 52937.9922 - mae: 52937.9922 - val_loss: 52073.5859 - val_mae: 52073.5859
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 51423.3555 - mae: 51423.3555 - val_loss: 51288.7266 - val_mae: 51288.7266
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 50809.1094 - mae: 50809.1094 - val_loss: 51010.3320 - val_mae: 51010.3320
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 50543.9883 - mae: 50543.9883 - val_loss: 50874.0664 - val_mae: 50874.0664
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 50408.8711 - mae: 50408.8711 - val_loss: 50787.8242 - val_mae: 50787.8242
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 50317.1328 - mae: 50317.1328 - val_loss: 50727.4258 - val_mae: 50727.4258
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 50244.4414 - mae: 50244.4414 - val_loss: 50679.0586 - val_mae: 50679.0586
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 50180.8594 - mae: 50180.8594 - val_loss: 50640.7617 - val_mae: 50640.7617
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 50132.3008 - mae: 50132.3008 - val_loss: 50599.8086 - val_mae: 50599.8086
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 50086.6211 - mae: 50086.6211 - val_loss: 50565.2148 - val_mae: 50565.2148
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 50045.1406 - mae: 50045.1406 - val_loss: 50524.7422 - val_mae: 50524.7422
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 50004.5547 - mae: 50004.5547 - val_loss: 50500.9648 - val_mae: 50500.9648
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49971.4727 - mae: 49971.4727 - val_loss: 50477.3047 - val_mae: 50477.3047
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49937.1797 - mae: 49937.1797 - val_loss: 50457.9453 - val_mae: 50457.9453
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49909.8906 - mae: 49909.8906 - val_loss: 50434.1992 - val_mae: 50434.1992
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49881.5117 - mae: 49881.5117 - val_loss: 50417.7461 - val_mae: 50417.7461
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49858.7656 - mae: 49858.7656 - val_loss: 50400.6992 - val_mae: 50400.6992
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49837.3789 - mae: 49837.3789 - val_loss: 50391.1914 - val_mae: 50391.1914
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49816.0430 - mae: 49816.0430 - val_loss: 50373.2031 - val_mae: 50373.2031
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49793.4805 - mae: 49793.4805 - val_loss: 50361.8242 - val_mae: 50361.8242
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49776.6719 - mae: 49776.6719 - val_loss: 50343.9688 - val_mae: 50343.9688
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49761.8047 - mae: 49761.8047 - val_loss: 50338.3438 - val_mae: 50338.3438
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 49738.7031 - mae: 49738.7031 - val_loss: 50326.4414 - val_mae: 50326.4414
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49722.3438 - mae: 49722.3438 - val_loss: 50316.7578 - val_mae: 50316.7578
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49708.5664 - mae: 49708.5664 - val_loss: 50314.1094 - val_mae: 50314.1094
Epoch 35/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49693.1758 - mae: 49693.1758 - val_loss: 50309.4609 - val_mae: 50309.4609
Epoch 36/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49678.5195 - mae: 49678.5195 - val_loss: 50295.5117 - val_mae: 50295.5117
Epoch 37/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49665.4414 - mae: 49665.4414 - val_loss: 50292.6914 - val_mae: 50292.6914
Epoch 38/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49650.1094 - mae: 49650.1094 - val_loss: 50290.9336 - val_mae: 50290.9336
Epoch 39/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49641.7461 - mae: 49641.7461 - val_loss: 50288.8125 - val_mae: 50288.8125
Epoch 40/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49628.3906 - mae: 49628.3906 - val_loss: 50287.0938 - val_mae: 50287.0938
Epoch 41/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49615.5273 - mae: 49615.5273 - val_loss: 50294.0703 - val_mae: 50294.0703
Epoch 42/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49606.0039 - mae: 49606.0039 - val_loss: 50296.3555 - val_mae: 50296.3555
Epoch 43/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49593.2852 - mae: 49593.2852 - val_loss: 50288.6914 - val_mae: 50288.6914
Epoch 44/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49586.5312 - mae: 49586.5312 - val_loss: 50293.4023 - val_mae: 50293.4023
Epoch 45/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49574.6406 - mae: 49574.6406 - val_loss: 50289.4258 - val_mae: 50289.4258
Epoch 46/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49565.6250 - mae: 49565.6250 - val_loss: 50287.5508 - val_mae: 50287.5508
Epoch 47/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49555.8867 - mae: 49555.8867 - val_loss: 50293.0391 - val_mae: 50293.0391
Epoch 48/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49546.9727 - mae: 49546.9727 - val_loss: 50285.9375 - val_mae: 50285.9375
Epoch 49/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49538.9727 - mae: 49538.9727 - val_loss: 50285.2109 - val_mae: 50285.2109
Epoch 50/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 49531.3867 - mae: 49531.3867 - val_loss: 50288.1602 - val_mae: 50288.1602
Epoch 51/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49525.2617 - mae: 49525.2617 - val_loss: 50294.0781 - val_mae: 50294.0781
Epoch 52/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49514.3555 - mae: 49514.3555 - val_loss: 50299.3164 - val_mae: 50299.3164
Epoch 53/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - loss: 49509.6523 - mae: 49509.6523 - val_loss: 50302.0625 - val_mae: 50302.0625
Epoch 54/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 4s 16ms/step - loss: 49505.6914 - mae: 49505.6914 - val_loss: 50297.1797 - val_mae: 50297.1797
Epoch 55/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 4s 16ms/step - loss: 49494.7383 - mae: 49494.7383 - val_loss: 50301.5469 - val_mae: 50301.5469
Epoch 56/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 5s 15ms/step - loss: 49489.3594 - mae: 49489.3594 - val_loss: 50308.2266 - val_mae: 50308.2266
Epoch 57/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - loss: 49484.1758 - mae: 49484.1758 - val_loss: 50305.8633 - val_mae: 50305.8633
Epoch 58/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 49478.1523 - mae: 49478.1523 - val_loss: 50313.6719 - val_mae: 50313.6719
Epoch 59/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 6s 17ms/step - loss: 49474.3164 - mae: 49474.3164 - val_loss: 50309.9531 - val_mae: 50309.9531

In [29]:
%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

In [25]:
%tensorboard --logdir regressionlogs/fit

In [26]:
## Evaluate model on the test data
test_loss,test_mae=model.evaluate(X_test,y_test)
print(f'Test MAE : {test_mae}')

63/63 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 50285.2109 - mae: 50285.2109
Test MAE : 50285.2109375

In [27]:
model.save('regression_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.